####
# ATENTION:
# Replace all occurences of sandbox with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  mysql-data-app:
    driver: local

  # Redis Data
  redis-data-app:
    driver: local

services:

  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: mysql-app
    volumes:
      - mysql-data-app:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sandbox
      - MYSQL_DATABASE=sandbox
      - MYSQL_USER=sandbox
      - MYSQL_PASSWORD=sandbox

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: redis-app
    command: --appendonly yes
    volumes:
      - redis-data-app:/data
    ports:
      - "6379:6379"

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.0-caddy
    container_name: sandbox-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.0
    container_name: queue-app
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache